version: "3"
services:
  nginx:
    build: nginx
    ports:
      - 8000:80
    links:
      - backend 
  db:
    build: postgres
    environment:
      POSTGRES_PASSWORD: docker
  backend:
    build: backend
    ports:
      - 3000:3000
    links:
      - db
    environment:
      PGRST_DB_URI: db
      PGRST_SERVER_HOST: db
