version: "3"
services:
  nginx:
    build: nginx
    ports:
      - 8000:80
    links:
      - backend 
  backend:
    build: backend
    links:
      - db
    depends_on:
      - db_init
    environment:
      PGRST_DB_URI: db
      PGRST_SERVER_HOST: db
  db:
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: api
  db_init:
    image: postgres:9.6.3-alpine
    command: echo "CREATE DATABASE api" | psql --host=db
